---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.colly.serviceName }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    name: {{ .Values.colly.serviceName }}
  name: {{ .Values.colly.serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.colly.serviceName }}
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.18.2
      labels:
        name: {{ .Values.colly.serviceName }}
        app.kubernetes.io/name: {{ .Values.colly.serviceName }}
        app.kubernetes.io/version: {{ .Chart.Version }}
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: {{ .Values.colly.db.host }}
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ .Values.colly.serviceName }}-secret
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Values.colly.serviceName }}-secret
            - name: ENV_INSTANCES_REPO
              value: {{ .Values.colly.instancesRepo }}
            - name: CRON_SCHEDULE
              value: {{ .Values.colly.cronSchedule }}
            - name: QUARKUS_OIDC_AUTH_SERVER_URL
              value: {{ .Values.colly.idp.url }}
            - name: QUARKUS_OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: idpClientId
                  name: {{ .Values.colly.serviceName }}-secret
            - name: QUARKUS_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: idpClientSecret
                  name: {{ .Values.colly.serviceName }}-secret
          image: {{ .Values.colly.image }}
          imagePullPolicy: Always
          name: qubership-colly
          ports:
            - containerPort: {{ .Values.colly.ports.http }}
              name: web
              protocol: TCP
